### ISSUE TITLE
[REFACTOR] 챌린지 유효성 검사 

### ISSUE THREAD

**Issue by eunjin210** [kakao-tech-campus-2nd-step3/Team15_FE#156]
## 📄 Description
설명 작성하세요.

## ✅ TODO
- [x] 인증글 작성시 하루에 하나만 인증글 작성 가능 
- [x] 챌린지 참여시 내가 보유한 포인트 초과로 참여 포인트 입력 불가 (1원 이상 1000,000 이하)

## 🎸 ETC

**Comment by joshuayeyo** [comment]
이거 왜 Assignee 저인가요

**Comment by eunjin210** [comment]
수정했습니당
